### ISSUE TITLE
[🤷🏼 Support]: Whats wrong?

### ISSUE THREAD

**Issue by alw-agent** [litecoin-foundation/litewallet-android#113]
***This ticket was escalated from Zendesk by Kerry Washington:***

  **Ticket:** [#3105](https://litecoinfoundation.zendesk.com/agent/tickets/3105)
  **Type:** Incident
  **Priority:** -
  **Requester:** Александр Артеменко
  **Organization:** -
  **Assignee:** Kerry Washington
***

Issue created by the Litewallet Support team and usually from a **problem** or `bug`

Attachments:<br/> [VID-20221203-WA0001.mp4](https://litecoinfoundation.zendesk.com/attachments/token/LBhtwrs58thlkjcnGzU9HjYBq/?name=VID-20221203-WA0001.mp4)<br><br><i>(created from <a href='https://litecoinfoundation.zendesk.com/agent/tickets/3105'>Zendesk ticket #3105</a>)<br> </i>

**Comment by kcw-grunt** [comment]
practice
