### ISSUE TITLE
🦟[Bug Report] Crashlytics: BRKeyStore._getData Exceptions at Runtime

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#126]
## Description

The remnants of the old Bread server architecture relied on making a Keystore and updating it remotely when the user launched the app.  This was never part of the design philosophy of Litewallet. 

### Developer Intent

Originally, the Breadwallet developers wanted to create a encrypted keystore when the user created a 'Breadwallet' then they wanted the user to sync the changes to the database and update the keystore.  The getData is the attempt to synchronize that keystore with the user so if they lose the keystore, they can pay Breadwallet to restore the information.

So in the method `private synchronized static byte[] _getData`  the are checking to see if that is all working. They are throwing an exception on this method (UserNotAuthorized) by treating it as a malicious attack.

## Problems with BRKeyStore._getData

Litewallet and the original fork (called Loafwallet) never had a cloud architecture.  This is because, our mission is to not collect any PII (Personal Identifiable Information) for Litewallet / Litecoin users. So, there was never a syncing server...and there will not be.

But we still need to call this method to unlock the users Keystore. The crashes happen because somehow that the KeyStore fails
 
 The try/catch chain is horrific.  There is no graceful design ...IMHO.
 If you look you can see one of the exceptions (all of them?):
 	- InvalidKeyException 
	-  UserNotAuthenticatedException
 	- IOException 
	- CertificateException
	- KeyStoreException
	- RuntimeException
 	- UnrecoverableKeyException
	- NoSuchAlgorithmException
	- NoSuchPaddingException
	- InvalidAlgorithmParameterException
	
Naturally, these exceptions happen often. I feel there needs to be a bulletproof way to handle this.  Even if it fails, there should be something meaningful for the user.  

---
**Any calls to a remote user keystore will never  be part of the business logic of Litewallet**
---

We need to remove any errant calls to this phantom keystore and refactor (REMOVE) this code and squash the bug

## Stack trace (via Crashlytics)
 
https://console.firebase.google.com/u/0/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/c4650474272086b7269389b8d857d62e?time=last-seven-days&sessionEventKey=63D7BB41008000015764C66E3776A37B_1772870423120895334

**Comment by kcw-grunt** [comment]
cc: @andhikayuana

**Comment by andhikayuana** [comment]
do you have step to reproduce this issue? @kcw-grunt or @josikie

**Comment by kcw-grunt** [comment]
Closing this ticket and reissuing a [follow](https://github.com/litecoin-foundation/litewallet-android/issues/288) on to further investigate
