### ISSUE TITLE
🥳 [Feature] Android Accepts and sends bech32 addresses

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#14]
# Goal
Litewallet Android accepts and sends bech32 (1ltc...) addresses

# Definition of Done

- [ ]  Updated loafwallet-core submodule with bech32 changes
- [ ] Unit tests that checks different address types
- [ ] GIF in of the new action in PR

#  History 
https://github.com/litecoin-foundation/loafwallet-core/issues/22
https://github.com/litecoin-foundation/loafwallet-core/pull/19

**Comment by kcw-grunt** [comment]
1. Started this work by branching from develop to work on branch: feature/test-bech32
2. Updated the loafwallet-core submodule to the branch ```test-bech32``` last commit (6809bf8bef7124902b4dfffaa7b93d11d59c9ade)
```
grunt@Kerrys-MacBookPro2 loafwallet-core % gs
HEAD detached at 2ea83a2
nothing to commit, working tree clean
grunt@Kerrys-MacBookPro2 loafwallet-core % git checkout 6809bf8bef7124902b4dfffaa7b93d11d59c9ade
Previous HEAD position was 2ea83a2 Merge pull request #14 from mosadialiou/fix-testnet
HEAD is now at 6809bf8 🦺Updated the checkpoints: Android branch (#24)
grunt@Kerrys-MacBookPro2 loafwallet-core % 
```
3. Waiting on a thorough look from @losh11  on the changes but we can try to get it working or look at it.
4. Make a Closed testing release for more testers
5.  Finalize to approve all changes 
6. Promote the release to Open Testing then Production
---

cc:  @coblee . @vsima , @losh11

**Comment by losh11** [comment]
FYI the `test-bech32`branch of loafwallet-core is intended for both iOS and Android. 
In the past Android and iOS shared the same branch, but due to an API break, I had only gotten towards upgrading to the new API on iOS.
