### ISSUE TITLE
🦺[Tech Debt] Add Analytics Event for Litecoin Card users in Litewallet

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#142]
## Goal 
**Describe the work to be done**
 
We need to count how many active users access their Litecoin Card through the Litewallet interface

## Why?
We need to understand if the user growth will affect our support needs.
 
## Definition of Done
- [ ] Add Google Analytics custom event to trigger "did_login_litecoincard_portal" 
- [ ] Test by logging in and out of the Litecoin Card through Litewallet
- [ ] Verify in Google Analytics

**Comment by kcw-grunt** [comment]
Hey @josikie!

Let's build our own meter to see where the Litecoin Card usage is so we can anticipate it.

**Comment by josikie** [comment]
Hi! @kcw-grunt 
I added the 'did_login_litecoincard_portal' Google Analytics Custom, can you test it by logging in and out of the Litecoin Card? I don't have Litecoin Card yet
