### ISSUE TITLE
🥳[Feature]Desktop Version? 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#144]
## Overview
Currently, Litewallet  is built for mobile but having a SPV Desktop version has been requested.
### Why?
**Is your request related to a problem? Or, do you have an idea to improve the app? Please describe.**
 
The a desktop version would be quicker and less resource intensive than a full-chain option.

### What?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 

### Definition of Done
- [ ] Action 1
- [ ] Action 2
- [ ] Action N

## UI Changes

|**Before**|**After**|
|----------|---------|
|||

**Comment by TheeTw23** [comment]
I never requested this

Wayne B. Kimball

**Comment by kcw-grunt** [comment]
Will not do.
