### ISSUE TITLE
💡[Request] Can we get litewallet APK and/or fdroid repo made available please?

### ISSUE THREAD

**Issue by Final-Phoenix** [litecoin-foundation/litewallet-android#156]
Would be nice for those that don't trust or want to go through Google Play Store

**Comment by TheeTw23** [comment]
Add in guideline docs

**Comment by kcw-grunt** [comment]
Looking into it: @Final-Phoenix

**Comment by kcw-grunt** [comment]
Update: @Final-Phoenix @TheeTw23 
Fdroid is not going to be a possiblity because:

- Fdroid doesnt allow Firebase which is integral to our management of Litewallet

**Comment by kcw-grunt** [comment]
No Fdroid...looking of posting APK in litewallet.io
