### ISSUE TITLE
🐞[Bugfix] Wrong Litecoin Card link in Android code

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#16]
##  Problem
The Litecoin Card URL to the Ternio backend is incorrect 

## From Support

> This is a follow-up to your previous request [#658](https://litecoinfoundation.zendesk.com/agent/tickets/658) "Litecoin card integration"
> 
> Hi, I think I figured out the issue with the litecoin card integration and litewallet for android. The login isn't recognized because the the login for the app goes through litecoin.dev.blockcard.ternio.com instead of the URL for regular accounts, so this would be searching any accounts on whatever that dev tenant is for the login.

## Environment

- Android 12
- Pixel 5a

**Comment by ROSASmith** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Litecoin  support [LIVE CHAT ](litte-coin.com)

**Comment by kcw-grunt** [comment]
resolved by fixing #82
