### ISSUE TITLE
🥳[Feature] Update the lock screen

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#160]
## Overview
We need to match the lock screen to show updates for the user

### Why?
Parity with iOS v3.12.0

### What?
**Describe the solution you'd like**
Add a view like used in v3.12.0 (Litewallet iOS)

### Definition of Done
- [ ] Note the blue is a different shade. Its now : **0C3475**
- [ ] Submit a draft PR for review

| Proposed Lock Screen View | 
|----------------------------|
|![new-lock-v3 12 0](https://github.com/litecoin-foundation/litewallet-android/assets/2899463/2eec5413-cf90-4fd5-bb0b-cbf7d9ecb1c8)|

**Comment by josikie** [comment]
Hello @kcw-grunt 
I want to create a new branch, from which branch I could checkout the new branch? Is it the develop branch or release/v2.9.0-experimental branch or release/v2.9.0 branch?
