### ISSUE TITLE
Allow Litewallet users to manually select an IPv6 node

### ISSUE THREAD

**Issue by Odontoceti** [litecoin-foundation/litewallet-android#191]
# Problem
Litewallet currently rejects the input of IPv6 IP addresses as if they were non-valid addresses or domain names. The option to manually select a node is under the advanced settings menu and it only allows IPv4 addressess for now.

The reason for this apparently is the module ```TrustedNode.java```. This module performs the validation of what the user inputs, and whether it contains a port or not. It's programmed in such a way that only IPv4 is considered valid.

# Solution
In order for Litewallet to allow IPv6 addressess a modification or rewrite of at least this module would be required. I may have missed other parts or got it entirely wrong.

# Affected users
* Users that manually select the node they want to connect to.
     * Out of that population, the even smaller percentage that wants to connect to an IPv6 addressed node.

**Comment by kcw-grunt** [comment]
Thanks for posting this issue @Odontoceti .

As mentioned before this is an extremely rare corner case for Litewallet users and we are struggling for any reason to escalate at this time. We don't really see this as a problem.

Can you provide examples where other wallets have already adopted  IPv6 capability?  Please provide code links.

**Comment by kcw-grunt** [comment]
# CLOSE
