### ISSUE TITLE
option to disable forced donation

### ISSUE THREAD

**Issue by DopamineUser** [litecoin-foundation/litewallet-android#194]
you should either allow disabling of the forced "donation" through advanced settings, or at least post an apk without it here on github that won't be getting more updates i guess. i don't want to switch to another wallet but you're forcing it.. i've been using litewallet for years and donated a few bucks, and then you do this :/

you are the only non-custodial wallet that does this.

**Comment by kcw-grunt** [comment]
Sorry, its not a donation.  Its the only way we can pay for mainentance.  You can just use Newborn if you don't like paying $0.01

No argument whatsoever.

**Comment by DopamineUser** [comment]
link to newborn?

if it was 1 cent nobody would be complaining, but no, it's 1% to 1.83%, capping at 2.75 EUR. i pay 0.5% for a non-custodial exchange, and the exchange provider is at risk of loss. but you charge me 2-3.5x more than an exchange does, JUST for sending a transaction through your app + you have 0 risk. i have to pay you 1.83 EUR for a 100 EUR transaction. which is 183 TIMES more than the economy transaction fee. you see nothing wrong with that?



still can't believe you said it's 1 cent, if only it was.

**Comment by DopamineUser** [comment]
@kcw-grunt
