### ISSUE TITLE
🦺[Tech Debt] Remove AnnounceView

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#209]
## Goal 
**Describe the work to be done**
 
The AnnounceView was meant to encourage users to give and email. But, that is not a strategy we are pursuing.

## Definition of Done
- [x] Remove the view
- [x] Test

**Comment by josikie** [comment]
Noted! @kcw-grunt

**Comment by kcw-grunt** [comment]
Done !
