### ISSUE TITLE
litewallet does not work wih litecoind 0.21.2.1

### ISSUE THREAD

**Issue by MoneroArbo** [litecoin-foundation/litewallet-android#24]
Using litewallet Android v2.6.1 -- when connecting to my home node running litecoind v0.21.2.1 I get stuck at 'Syncing' and the sync does not progress. Was previously working with litecoind v0.18.1.

debug.log for litecoind shows some errors "socket send error Connection timed out (110)" and "socket send error Connection reset by peer (104)" when trying to connect litewallet to it.

litewallet displays no error messages I can see unless there's a log somewhere.

Happy to collect or give any information that would help

**Comment by losh11** [comment]
Block filters were disabled by default in Litecoin Core 0.21.x. Please use
0.18. In the future Litewallet will support BIP157/158 and you will once
again be able to connect to 0.21+ nodes.

**Comment by MoneroArbo** [comment]
Awesome thank you!

I set peerbloomfilters=1 in litecoin.conf and now litewallet seems to be working fine with 0.21.2.1

**Comment by kcw-grunt** [comment]
Thanks @losh11 

Closing!
