### ISSUE TITLE
🐛[Bug Report]: AuthPrompt is the source of many crashes

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#241]
### Device model

A wide number of devices are experiencing this crash

|  App Crashes Distribution |
|-------------------------|
|![Screenshot 2024-10-06 at 8 17 37 PM](https://github.com/user-attachments/assets/a4c9789d-73c5-4300-a824-1ed64c264764)|

### OS version

Other

### Which version of Litewallet are you running?

Other

### Describe what happened.

1. User launches the app
2. The method causes crashes 
3.  In this case the app crashes

####  Firebase notes: 
https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/e62bd3b2c450bdc67fa703c10e2ce5db?time=1712994462715:1715586462715&sessionEventKey=664116C701AD00014458EB7DA4CD049D_1946818051493448057

#### Code snippet found 
Please see the method where the code is causing the problem. (In AuthManager.java) on lines in 218, 231

```   
public void authPrompt(final Context context, String title, String message, boolean forcePin, boolean forceFingerprint, BRAuthCompletion completion)
````

**Comment by josikie** [comment]
Ok, noted!

**Comment by kcw-grunt** [comment]
we are working on this!

**Comment by kcw-grunt** [comment]
cc: @andhikayuana

We will need your review
