### ISSUE TITLE
🪲[Bugfix] Utils.fetchPartnerKey OOM Error

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#258]
## Description
There are some special parts of the app which are needs for various steps at runtime.  99.9% this part is available but there are still cases where the user experiences a Out of Memory Error and crash

## Stack trace (via Crashlytics)

https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/5235759c1a47bb04a3f4f276b5195701?time=last-seven-days&types=crash&sessionEventKey=67296E0501B6000141A67CD9AF21CFFB_2012052907173496268

## Definition of Done

- [x] Identify reason for the OOM Error
- [x] Remedy the situation
- [x] Test and submit PR

**Comment by andhikayuana** [comment]
So far I found after read the code, it's about `fetchPartnerKey` called every `setTexts` called inside the viewholder (depends on the list size)

**Comment by kcw-grunt** [comment]
Merged
