### ISSUE TITLE
🐛[Bug Report]: Utils.fetchPartnerKey

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#266]
## Problem
Utils is throwing this exception at runtime

### Crashlytics Stacktrace
https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/3cf9517d12b08897691d9a9125075a42?time=last-seven-days&types=crash&sessionEventKey=672F4ED5039E00014CE26277EF1AE59E_2013694765954212001

### App (Poor) Performance 
Please refer to AS for details

**Comment by andhikayuana** [comment]
the crashlytics link that you're mentioned above is for `Utils.tieredOpsFee` is it correct? since the title is `Utils.fetchPartnerKey`

**Comment by kcw-grunt** [comment]
They are related.

**Comment by kcw-grunt** [comment]
merged
