### ISSUE TITLE
🐛[Bug Report]: Welcome screen Locale/Language and audio are not activated properly

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#274]
### Device model

All

### OS version

Android 14 | Level 34 (Default)

### Which version of Litewallet are you running?

Other

### Describe what happened.

1. Go to ...
2. Tap on ...
3. Error, error! 🦑🔥

### Add any notes you would like to add.

# Problem
When the first time user sees the welcome screen the locale selection is not persisting when they open the app.  So, they are neveer able to use their locale language. **This only happens for first time users**

The key is that sometimes the feature works, but the picker sometimes is stuck in a state where the language is not set and defaults to English....this is bad

## Regression
This worked previously and is was highly effective in getting users to onboard and use Litewallet.
The good news is this a relatively new feature so it shouldnt take long to understand the business logic

## Screenshot Clip

| Clip |
|------|
|![welcome-bug](https://github.com/user-attachments/assets/2fd1644e-0f14-4939-94c1-5ae2e77d3ee3)|
 
##  Definition of Done

- [ ] Ensure the welcome screen plays the local language and when the user selects it, the app shows that locale
- [ ] Ensure that when the existing users are changing the language, it effectively switches to that language
- [ ] PR should explain a description of where the bug caused the issue and a how it was fixed
- [ ] Add 2 Tests to further protect the work and business logic

**Comment by andhikayuana** [comment]
about audio not playing, maybe the audio not downloaded yet since using play asset delivery

**Comment by kcw-grunt** [comment]
Closing...this was resolved in v2.12.4 20241130 . Thanks @andhikayuana
