### ISSUE TITLE
About litewallet observation pattern technology please teach

### ISSUE THREAD

**Issue by vcexnet** [litecoin-foundation/litewallet-android#3]
hi, @mosadialiou I would like to know if spv mode can implement the observation mode.
For example I know an address and synchronize the information of that address through watch mode. Just to view. I don't have the ownership of this address. I wonder if this is possible? Or even to observe multiple addresses?
I'm confused about this and would like to get technical help, thanks!
I don't know if spv mode can be implemented. I'm confused about this and would like to get technical help on it, thanks!

**Comment by kcw-grunt** [comment]
Sorry..we are out of time to train others  @vcexnet.  If you want to pick up an issue, we can do a code review
