### ISSUE TITLE
🥳[Feature]

### ISSUE THREAD

**Issue by erc155** [litecoin-foundation/litewallet-android#65]
### Why?
**Is your request related to a problem? Or, do you have an idea to improve the app? Please describe.**
 

### What?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 

### Definition of Done
- [x] Action 1
- [x] Action 2
- [x] Action N

## UI Changes

|**Before**|**After**|
|----------|---------|
|||

**Comment by kcw-grunt** [comment]
Dupe/Mistake
