### ISSUE TITLE
🦟[Bug Report] Cannot copy the Transaction TXID

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#68]
**Describe the bug**
from:  @Crypto-Keeper-miners 
I do see an issue myself on the wallet, when you click a transaction, you cannot copy the TXID nor does the link work to the block explorer. I am using Android. After it times out it says Browser (YOU) Working, (Denver) Cloudflare working, HOST ERROR ([insight.litecore.io](http://insight.litecore.io/))

**Expected behavior**

**Screenshots or GIFs**
If applicable, add screenshots or GIFs to help explain your problem.

**Mobile device (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 25]
 - Litewallet Version [e.g. v1.19.3]

**Additional context**

**Comment by kcw-grunt** [comment]
cc: @Crypto-Keeper-miners

**Comment by Crypto-Keeper-miners** [comment]
I am wondering if this issue is being addressed?
